# $Id: Makefile,v 1.1 2005/07/18 17:22:16 schaum Exp $

all:
	cd ./aes;        make ; cd .
	cd ./euclid;     make ; cd .
	cd ./ipchecksum; make ; cd .

sim:
	cd ./aes;        make sim sim1 sim2; cd .
	cd ./euclid;     make sim sim1 sim2; cd .
	cd ./ipchecksum; make sim sim1 sim2; cd .

clean:
	cd ./aes;        make clean; cd .
	cd ./euclid;     make clean; cd .
	cd ./ipchecksum; make clean; cd .
